channels:
- conda-forge
dependencies:
- python=3.10.14
- pip<=24.0
- pip:
  - mlflow==2.13.2
  - cloudpickle==3.0.0
  - lightgbm==4.3.0
  - matplotlib==3.8.4
  - numpy==1.26.4
  - packaging==24.0
  - pandas==2.2.2
  - pyarrow==15.0.2
  - scikit-learn==1.4.2
  - scipy==1.13.0
name: mlflow-env
