# name: Deploy MLServer

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2

#     - name: Set up Docker Buildx
#       uses: docker/setup-buildx-action@v1

#     - name: Login to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_USERNAME }}
#         password: ${{ secrets.DOCKER_PASSWORD }}

#     - name: Build and push MLServer image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./mlserver
#         push: true
#         tags: |
#           esshin94/mlserver:${{ github.sha }}
#           esshin94/mlserver:latest

#     - name: Deploy to Server
#       uses: appleboy/ssh-action@master
#       with:
#         host: ${{ secrets.SERVER_HOST }}
#         username: ${{ secrets.SERVER_USERNAME }}
#         key: ${{ secrets.SERVER_SSH_KEY }}
#         script: |
#           # Pull the new image
#           docker pull esshin94/mlserver:${{ github.sha }}
#           sh rolling_update.sh